// State colors for visual feedback
export const STATE_COLORS = {
	DEFAULT: new Color3(0.7, 0.7, 0.7), // Grey
	HIGHLIGHTED: new Color3(0.2, 0.4, 0.8), // Blue
} as const;

// US States and their capitals
export const US_STATES = {
	ALABAMA: "Alabama",
	ALASKA: "Alaska",
	ARIZONA: "Arizona",
	ARKANSAS: "Arkansas",
	CALIFORNIA: "California",
	COLORADO: "Colorado",
	CONNECTICUT: "Connecticut",
	DELAWARE: "Delaware",
	FLORIDA: "Florida",
	GEORGIA: "Georgia",
	HAWAII: "Hawaii",
	IDAHO: "Idaho",
	ILLINOIS: "Illinois",
	INDIANA: "Indiana",
	IOWA: "Iowa",
	KANSAS: "Kansas",
	KENTUCKY: "Kentucky",
	LOUISIANA: "Louisiana",
	MAINE: "Maine",
	MARYLAND: "Maryland",
	MASSACHUSETTS: "Massachusetts",
	MICHIGAN: "Michigan",
	MINNESOTA: "Minnesota",
	MISSISSIPPI: "Mississippi",
	MISSOURI: "Missouri",
	MONTANA: "Montana",
	NEBRASKA: "Nebraska",
	NEVADA: "Nevada",
	NEW_HAMPSHIRE: "New Hampshire",
	NEW_JERSEY: "New Jersey",
	NEW_MEXICO: "New Mexico",
	NEW_YORK: "New York",
	NORTH_CAROLINA: "North Carolina",
	NORTH_DAKOTA: "North Dakota",
	OHIO: "Ohio",
	OKLAHOMA: "Oklahoma",
	OREGON: "Oregon",
	PENNSYLVANIA: "Pennsylvania",
	RHODE_ISLAND: "Rhode Island",
	SOUTH_CAROLINA: "South Carolina",
	SOUTH_DAKOTA: "South Dakota",
	TENNESSEE: "Tennessee",
	TEXAS: "Texas",
	UTAH: "Utah",
	VERMONT: "Vermont",
	VIRGINIA: "Virginia",
	WASHINGTON: "Washington",
	WEST_VIRGINIA: "West Virginia",
	WISCONSIN: "Wisconsin",
	WYOMING: "Wyoming",
} as const;

export type StateName = typeof US_STATES[keyof typeof US_STATES];

// State capital data (for future features)
export const STATE_CAPITALS: Record<StateName, string> = {
	Alabama: "Montgomery",
	Alaska: "Juneau",
	Arizona: "Phoenix",
	Arkansas: "Little Rock",
	California: "Sacramento",
	Colorado: "Denver",
	Connecticut: "Hartford",
	Delaware: "Dover",
	Florida: "Tallahassee",
	Georgia: "Atlanta",
	Hawaii: "Honolulu",
	Idaho: "Boise",
	Illinois: "Springfield",
	Indiana: "Indianapolis",
	Iowa: "Des Moines",
	Kansas: "Topeka",
	Kentucky: "Frankfort",
	Louisiana: "Baton Rouge",
	Maine: "Augusta",
	Maryland: "Annapolis",
	Massachusetts: "Boston",
	Michigan: "Lansing",
	Minnesota: "Saint Paul",
	Mississippi: "Jackson",
	Missouri: "Jefferson City",
	Montana: "Helena",
	Nebraska: "Lincoln",
	Nevada: "Carson City",
	"New Hampshire": "Concord",
	"New Jersey": "Trenton",
	"New Mexico": "Santa Fe",
	"New York": "Albany",
	"North Carolina": "Raleigh",
	"North Dakota": "Bismarck",
	Ohio: "Columbus",
	Oklahoma: "Oklahoma City",
	Oregon: "Salem",
	Pennsylvania: "Harrisburg",
	"Rhode Island": "Providence",
	"South Carolina": "Columbia",
	"South Dakota": "Pierre",
	Tennessee: "Nashville",
	Texas: "Austin",
	Utah: "Salt Lake City",
	Vermont: "Montpelier",
	Virginia: "Richmond",
	Washington: "Olympia",
	"West Virginia": "Charleston",
	Wisconsin: "Madison",
	Wyoming: "Cheyenne",
};
